import sys
sys.stdout.reconfigure(encoding='utf-8')
path = 'D:/test/STM32H723ZGT6/host/widgets/wave_panel.py'
with open(path, 'r', encoding='utf-8') as f:
    c = f.read()

# 1: Replace rule_box stretch and add rule_io section
old1 = '        ctrl_layout.addWidget(rule_box, stretch=1)'
new1 = (
    '        ctrl_layout.addWidget(rule_box, stretch=3)\n'
    '\n'
    '        # --- 2b. Rule Import/Export ---\n'
    '        rule_io_box = QGroupBox("\u89c4\u5219\u5bfc\u5165\u5bfc\u51fa")\n'
    '        rule_io_layout = QVBoxLayout(rule_io_box)\n'
    '        rule_io_layout.setContentsMargins(6, 6, 6, 6)\n'
    '        self.btn_export_rules = QPushButton("\u5bfc\u51fa\u89c4\u5219\u81f3Excel")\n'
    '        self.btn_export_rules.clicked.connect(self._export_rules_excel)\n'
    '        rule_io_layout.addWidget(self.btn_export_rules)\n'
    '        self.btn_import_rules = QPushButton("\u4eceExcel\u5bfc\u5165\u89c4\u5219")\n'
    '        self.btn_import_rules.clicked.connect(self._import_rules_excel)\n'
    '        rule_io_layout.addWidget(self.btn_import_rules)\n'
    '        rule_io_layout.addStretch()\n'
    '        ctrl_layout.addWidget(rule_io_box, stretch=2)'
)
assert old1 in c, 'm1'
c = c.replace(old1, new1, 1)
print('1 OK')

# 2: Insert rule export/import methods before Protocol section
old2 = '            self.log_signal.emit(f"[ERROR] Excel \u5bfc\u5165\u5931\u8d25: {e}")\n\n    # ============================================================\n    # Protocol'
new2 = (
    '            self.log_signal.emit(f"[ERROR] Excel \u5bfc\u5165\u5931\u8d25: {e}")\n'
    '\n'
    '    # ============================================================\n'
    '    # Rule Excel Import / Export\n'
    '    # ============================================================\n'
    '\n'
    '    def _export_rules_excel(self):\n'
    '        """Export timing rules (rule table + initial states) to Excel."""\n'
    '        from PyQt6.QtWidgets import QInputDialog\n'
    '        path, _ = QFileDialog.getSaveFileName(\n'
    '            self, "\u5bfc\u51fa\u65f6\u5e8f\u89c4\u5219", self._last_ie_dir,\n'
    '            "Excel Files (*.xlsx)")\n'
    '        if not path:\n'
    '            return\n'
    '        self._last_ie_dir = os.path.dirname(path)\n'
    '\n'
    '        data = self._gather_rules_data()\n'
    '        wb = openpyxl.Workbook()\n'
    '        ws = wb.active\n'
    '        ws.title = "\u89c4\u5219"\n'
    '\n'
    '        # Header\n'
    '        headers = ["\u901a\u9053", "\u89e6\u53d1\u7f16\u7a0b(Point)", "\u65f6\u5e8f\u7c7b\u578b", "\u6301\u7eed\u5bbd\u5ea6(Points)"]\n'
    '        for ci, h in enumerate(headers, 1):\n'
    '            ws.cell(row=1, column=ci, value=h)\n'
    '\n'
    '        # Write rules\n'
    '        rules = data.get("rules", [])\n'
    '        for ri, rule in enumerate(rules):\n'
    '            row_idx = ri + 2\n'
    '            ws.cell(row=row_idx, column=1, value=rule.get("channel", ""))\n'
    '            ws.cell(row=row_idx, column=2, value=rule.get("edge", 0))\n'
    '            ws.cell(row=row_idx, column=3, value=rule.get("level", ""))\n'
    '            ws.cell(row=row_idx, column=4, value=rule.get("width", 0))\n'
    '\n'
    '        # Also write initial states in a second sheet\n'
    '        ws2 = wb.create_sheet(title="\u521d\u59cb\u72b6\u6001")\n'
    '        ws2.cell(row=1, column=1, value="\u901a\u9053")\n'
    '        ws2.cell(row=1, column=2, value="\u521d\u59cb\u7535\u5e73")\n'
    '        init_states = data.get("initial_states", {})\n'
    '        for i, ch in enumerate(CH_NAMES):\n'
    '            ws2.cell(row=i + 2, column=1, value=ch)\n'
    '            ws2.cell(row=i + 2, column=2, value=init_states.get(ch, "\u4f4e"))\n'
    '\n'
    '        wb.save(path)\n'
    '        self.log_signal.emit(f"[INFO] \u65f6\u5e8f\u89c4\u5219\u5df2\u5bfc\u51fa\u5230 {path}")\n'
    '        QMessageBox.information(self, "\u5bfc\u51fa\u6210\u529f",\n'
    '            f"\u65f6\u5e8f\u89c4\u5219\u5df2\u5bfc\u51fa: {os.path.basename(path)}")\n'
    '\n'
    '    def _import_rules_excel(self):\n'
    '        """Import timing rules from Excel (editable, loads into rule table)."""\n'
    '        path, _ = QFileDialog.getOpenFileName(\n'
    '            self, "\u4eceExcel\u5bfc\u5165\u65f6\u5e8f\u89c4\u5219", self._last_ie_dir,\n'
    '            "Excel Files (*.xlsx)")\n'
    '        if not path:\n'
    '            return\n'
    '        self._last_ie_dir = os.path.dirname(path)\n'
    '\n'
    '        try:\n'
    '            wb = openpyxl.load_workbook(path, data_only=True)\n'
    '            ws = wb.active\n'
    '            if ws is None:\n'
    '                ws = wb.worksheets[0]\n'
    '\n'
    '            max_row = ws.max_row\n'
    '            if max_row < 2:\n'
    '                QMessageBox.warning(self, "\u5bfc\u5165\u5931\u8d25", "\u4e0d\u5b58\u5728\u89c4\u5219\u6570\u636e\u3002")\n'
    '                return\n'
    '\n'
    '            # Clear existing rules\n'
    '            self.rule_table.setRowCount(0)\n'
    '\n'
    '            # Read rules from sheet 1 (2..max_row)\n'
    '            for row in range(2, max_row + 1):\n'
    '                ch = ws.cell(row=row, column=1).value\n'
    '                edge = ws.cell(row=row, column=2).value\n'
    '                level = ws.cell(row=row, column=3).value\n'
    '                width = ws.cell(row=row, column=4).value\n'
    '                if not ch:\n'
    '                    continue\n'
    '                # Add rule row (replicates _add_rule logic)\n'
    '                r = self.rule_table.rowCount()\n'
    '                self.rule_table.insertRow(r)\n'
    '                ch_combo = QComboBox()\n'
    '                for name in CH_NAMES:\n'
    '                    if name == "SCLK":\n'
    '                        continue\n'
    '                    ch_combo.addItem(name)\n'
    '                idx = ch_combo.findText(str(ch))\n'
    '                if idx >= 0:\n'
    '                    ch_combo.setCurrentIndex(idx)\n'
    '                self.rule_table.setCellWidget(r, 0, ch_combo)\n'
    '\n'
    '                edge_spin = QSpinBox()\n'
    '                edge_spin.setRange(0, 4096)\n'
    '                try:\n'
    '                    edge_spin.setValue(int(edge))\n'
    '                except (TypeError, ValueError):\n'
    '                    edge_spin.setValue(0)\n'
    '                self.rule_table.setCellWidget(r, 1, edge_spin)\n'
    '\n'
    '                level_combo = QComboBox()\n'
    '                level_combo.addItems(["\u9ad8", "\u4f4e"])\n'
    '                idx_lv = level_combo.findText(str(level))\n'
    '                if idx_lv >= 0:\n'
    '                    level_combo.setCurrentIndex(idx_lv)\n'
    '                self.rule_table.setCellWidget(r, 2, level_combo)\n'
    '\n'
    '                width_spin = QSpinBox()\n'
    '                width_spin.setRange(0, 4096)\n'
    '                try:\n'
    '                    width_spin.setValue(int(width))\n'
    '                except (TypeError, ValueError):\n'
    '                    width_spin.setValue(0)\n'
    '                width_spin.setToolTip("0=\u6c38\u4e45\u4fdd\u6301\uff1bN=\u4ece\u89e6\u53d1\u70b9\u8d77\u6301\u7eedN\u4e2aCLK\u5468\u671f(1CLK\u5468\u671f=2\u91c7\u6837\u70b9)")\n'
    '                self.rule_table.setCellWidget(r, 3, width_spin)\n'
    '\n'
    '                btn = QPushButton("\u5220\u9664")\n'
    '                btn.clicked.connect(lambda checked, rr=r: self._remove_rule(rr))\n'
    '                self.rule_table.setCellWidget(r, 4, btn)\n'
    '\n'
    '            self._save_rules()\n'
    '            self.log_signal.emit(f"[INFO] \u4eceExcel\u5bfc\u5165\u4e86 {self.rule_table.rowCount()} \u6761\u65f6\u5e8f\u89c4\u5219")\n'
    '            QMessageBox.information(self, "\u5bfc\u5165\u6210\u529f",\n'
    '                f"\u5df2\u5bfc\u5165 {self.rule_table.rowCount()} \u6761\u65f6\u5e8f\u89c4\u5219\uff0c\u53ef\u4e8c\u6b21\u7f16\u8f91\u3002")\n'
    '\n'
    '        except Exception as e:\n'
    '            QMessageBox.critical(self, "\u5bfc\u5165\u5931\u8d25",\n'
    '                f"\u8bfb\u53d6\u89c4\u5219 Excel \u65f6\u51fa\u9519:\\n{str(e)}")\n'
    '            self.log_signal.emit(f"[ERROR] \u89c4\u5219 Excel \u5bfc\u5165\u5931\u8d25: {e}")\n'
    '\n'
    '    # ============================================================\n'
    '    # Protocol'
)
assert old2 in c, 'm2'
c = c.replace(old2, new2, 1)
print('2 OK')

with open(path, 'w', encoding='utf-8') as f:
    f.write(c)
import py_compile
py_compile.compile(path, doraise=True)
print('Syntax OK')
print('Done - ' + str(len(c.splitlines())) + ' lines')
