#include "app_wavegen.h"
#include "main.h"
#include <string.h>

/* External handles generated by CubeMX — ensure these exist in main.c/tim.c */
extern TIM_HandleTypeDef htim2;
extern DMA_HandleTypeDef hdma_tim2_up;

static uint32_t s_waveBuf[WAVE_MAX_POINTS];
static WaveConfig_t s_config = {0};
static volatile bool s_running = false;

/* Build BSRR mask from 5-bit channel state.
 * state bit0 -> PA0 (XYNC), bit1 -> PA1 (SCLK), bit2 -> PA2 (SH_R),
 * bit3 -> PA3 (SH_S), bit4 -> PA5 (RST)
 */
uint32_t APP_WaveGen_BuildBSRR(uint8_t state)
{
    uint32_t bsrr = 0;
    /* Set bits (low 16 bits of BSRR) */
    if (state & (1u << 0)) bsrr |= (1u << WAVE_CH0_BIT);
    if (state & (1u << 1)) bsrr |= (1u << WAVE_CH1_BIT);
    if (state & (1u << 2)) bsrr |= (1u << WAVE_CH2_BIT);
    if (state & (1u << 3)) bsrr |= (1u << WAVE_CH3_BIT);
    if (state & (1u << 4)) bsrr |= (1u << WAVE_CH4_BIT);
    /* Reset bits (high 16 bits of BSRR) */
    if (!(state & (1u << 0))) bsrr |= (1u << (WAVE_CH0_BIT + 16));
    if (!(state & (1u << 1))) bsrr |= (1u << (WAVE_CH1_BIT + 16));
    if (!(state & (1u << 2))) bsrr |= (1u << (WAVE_CH2_BIT + 16));
    if (!(state & (1u << 3))) bsrr |= (1u << (WAVE_CH3_BIT + 16));
    if (!(state & (1u << 4))) bsrr |= (1u << (WAVE_CH4_BIT + 16));
    return bsrr;
}

void APP_WaveGen_Init(void)
{
    memset(s_waveBuf, 0, sizeof(s_waveBuf));
    memset((void *)&s_config, 0, sizeof(s_config));
    s_running = false;
}

bool APP_WaveGen_Configure(const WaveConfig_t *cfg)
{
    if (cfg == NULL || cfg->num_points == 0 || cfg->num_points > WAVE_MAX_POINTS)
        return false;

    if (s_running) {
        APP_WaveGen_Stop();
    }

    s_config = *cfg;

    /* Configure TIM2 frequency:
     * TIM2 on H723 is on APB1 timer clock.
     * With default CubeMX 550 MHz core, APB1 timer clock is typically 275 MHz.
     * We'll use prescaler to get a reasonable range.
     * For simplicity, compute ARR to hit target sample_rate_hz.
     */
    uint32_t tim_clk = HAL_RCC_GetPCLK1Freq();
    /* On H7, if APB1 prescaler != 1, timer clock = 2 * PCLK1 */
    uint32_t apb1_div = (RCC->D2CFGR & RCC_D2CFGR_D2PPRE1_Msk) >> RCC_D2CFGR_D2PPRE1_Pos;
    if (apb1_div != RCC_D2CFGR_D2PPRE1_DIV1) {
        tim_clk *= 2;
    }

    uint32_t prescaler = 0;
    uint32_t period = 0;

    if (cfg->sample_rate_hz == 0 || cfg->sample_rate_hz > tim_clk) {
        return false;
    }

    /* Try to find prescaler and period */
    uint32_t ticks = tim_clk / cfg->sample_rate_hz;
    if (ticks == 0) ticks = 1;

    if (ticks <= 0xFFFF) {
        prescaler = 0;
        period = (uint16_t)(ticks - 1);
    } else {
        prescaler = (ticks / 0xFFFF);
        if (prescaler > 0xFFFF) prescaler = 0xFFFF;
        period = (uint16_t)((ticks / (prescaler + 1)) - 1);
    }

    __HAL_TIM_SET_PRESCALER(&htim2, prescaler);
    __HAL_TIM_SET_AUTORELOAD(&htim2, period);
    HAL_TIM_GenerateEvent(&htim2, TIM_EVENTSOURCE_UPDATE);

    return true;
}

bool APP_WaveGen_LoadData(const uint32_t *data, uint16_t len)
{
    if (data == NULL || len == 0 || len > WAVE_MAX_POINTS) return false;
    if (s_running) return false;

    memcpy(s_waveBuf, data, len * sizeof(uint32_t));
    s_config.num_points = len;
    return true;
}

bool APP_WaveGen_Start(void)
{
    if (s_running || s_config.num_points == 0) return false;

    /* Configure DMA from s_waveBuf to GPIOA->BSRR (circular mode, no IRQ needed) */
    HAL_DMA_Start(&hdma_tim2_up,
                  (uint32_t)s_waveBuf,
                  (uint32_t)&GPIOA->BSRR,
                  s_config.num_points);

    /* Enable TIM2 DMA request on update */
    __HAL_TIM_ENABLE_DMA(&htim2, TIM_DMA_UPDATE);

    /* Start TIM2 in normal mode (no output compare needed) */
    HAL_TIM_Base_Start(&htim2);

    s_running = true;
    return true;
}

void APP_WaveGen_Stop(void)
{
    if (!s_running) return;

    HAL_TIM_Base_Stop(&htim2);
    __HAL_TIM_DISABLE_DMA(&htim2, TIM_DMA_UPDATE);
    HAL_DMA_Abort(&hdma_tim2_up);

    s_running = false;
}

bool APP_WaveGen_IsRunning(void)
{
    return s_running;
}

const WaveConfig_t* APP_WaveGen_GetConfig(void)
{
    return &s_config;
}
